name: CI Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    # Variables de entorno para pruebas
    env:
      PYDANTICAI_ALLOW_MODEL_REQUESTS: 'false'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Setup Environment Variables
      run: |
        # Configurar valores predeterminados
        echo "WHATSAPP_TOKEN=test_token" >> $GITHUB_ENV
        echo "WHATSAPP_PHONE_NUMBER_ID=123456" >> $GITHUB_ENV
        echo "WHATSAPP_VERIFY_TOKEN_WEBHOOK=test_webhook" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=sk-test-dummy-key" >> $GITHUB_ENV
        echo "COSMOSDB_CONNECTION_STRING=mongodb://localhost:27017" >> $GITHUB_ENV
        
        # Log status
        echo "CI: Using default environment for testing"


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # Instalar dependencias de sistema necesarias para compilar algunas bibliotecas Python
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev
        # Instalar dependencias en modo verbose para ver errores detallados
        pip install -v -r requirements.txt
        pip install pytest pytest-cov pytest-html

    - name: Run core tests
      run: |
        pytest tests/ -v

    - name: Run agent tests
      run: |
        ./scripts/test_agents.sh

    - name: Test FastAPI application
      run: |
        ./test_fastapi.sh
        
    - name: Generate coverage report
      run: |
        pytest --cov=app --cov=agents --cov-report=xml --cov-report=html:
        mkdir -p coverage-reports
        mv coverage.xml coverage-reports/
        mv htmlcov coverage-reports/
      if: success()

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |  
          pytest-report.xml
          pytest-report.html
          coverage-reports/
        retention-days: 7
