name: Deploy to Azure Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: whatsapp-acktos-bot-2025
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Functions
      id: deploy
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    - name: Check deployment status and logs
      if: always()
      run: |
        echo "Getting deployment status..."
        az functionapp show --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group rg-whatsapp-bot --query state
        
        echo "Getting build logs..."
        az functionapp deployment source show --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group rg-whatsapp-bot
        
        echo "Getting function details..."
        az functionapp function show --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group rg-whatsapp-bot --function-name webhook || echo "Function not found"
        
        echo "Getting recent function invocations..."
        az monitor app-insights query --app whatsapp-acktos-bot-2025 --analytics-query "requests | where timestamp > ago(5m) | project timestamp, name, success, resultCode, duration, operation_Name"
